name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # build in docker
    - name: Build docker
      run: |
        docker build ./module01/src/myappspa -t cloudfield011acr.azurecr.io/myappspa:${{ github.sha }} -t cloudfield011acr.azurecr.io/myappspa:latest
        docker build ./module01/src/myapptodo -t cloudfield011acr.azurecr.io/myapptodo:${{ github.sha }} -t cloudfield011acr.azurecr.io/myapptodo:latest
        docker login cloudfield011acr.azurecr.io --username cloudfield011acr --password $DOCKERHUB_TOKEN
        docker push cloudfield011acr.azurecr.io/myappspa:${{ github.sha }}
        docker push cloudfield011acr.azurecr.io/myappspa:latest
        docker push cloudfield011acr.azurecr.io/myapptodo:${{ github.sha }}
        docker push cloudfield011acr.azurecr.io/myapptodo:latest
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'myrelease'
        namespace: 'myapp'
        chart: './module05/helm/myapp'
        helm: 'helm3'
        values: |
          appspa.image.repository: "cloudfield011acr.azurecr.io/myappspa"
          appspa.image.tag: '${{ github.sha }}'
          apptodo.image.repository: "cloudfield011acr.azurecr.io/myapptodo"
          apptodo.image.tag='${{ github.sha }}'
          apphost="52.143.250.69.xip.io"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
